### ISSUE TITLE
crash on server side only

### ISSUE THREAD

**Issue by amberwillow** [elytra/Engination-Fabric#1]
my server crashes when i add engination to it, my client doesnt seem to have any issues though.

https://pastebin.com/Whe9SsE4 contains the crashlog

Let me know if you need more info

**Comment by falkreon** [comment]
Oh! Huh! You just helped me track down a really weird problem I was happening with the mixin. Fix incoming shortly

**Comment by falkreon** [comment]
Fixed by 096d88c - curse update coming momentarily
