### ISSUE TITLE
Hooks for Epicurean

### ISSUE THREAD

**Issue by falkreon** [elytra/Engination-Fabric#3]
Will need input from @Boundarybreaker on this one- and maybe a companion issue on the other side.

Tomato and celery are foods. We should be able to make nice hearty stews or something. So:

* Tomato should be tagged `c:tomato`
* Celery should be tagged `c:celery`
* Both should be added to a `vegetables` tag, probably also in the `c` namespace.

If I'm missing something that would be helpful for EpiG or other mods to make use of the vegetables please let me know. Also, what conditions need to be satisfied for hopper-harvesting and other tweaks to work?

**Comment by LemmaEOF** [comment]
The only thing you need to do for hopper harvesting is make sure your crops extend `CropBlock`. I should really move to tag-based vegetables in recipes too, I'll do that when I have time.

**Comment by falkreon** [comment]
Added tags in 7d921e9, and following your `CropBlock` reccommendation. We should be all set on this end.
